services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-example}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-blow}
    volumes:
      - mongo_data:/data/db
    networks:
      - blow

  backend:
    build:
      context: ./blow-be
    depends_on:
      - mongo
    env_file:
      - ./deploy/env/backend.env
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    volumes:
      - ./blow-be/uploads:/app/uploads:rw   # ← bind из монорепо
    # volumes:
    #   - uploads_data:/app/uploads
    networks:
      - blow

  frontend:
    build:
      context: ./blow-fe
    depends_on:
      - backend
    env_file:
      - ./deploy/env/frontend.env
    environment:
      - NODE_ENV=production
    networks:
      - blow

  admin:
    build:
      context: ./blow-ap
    depends_on:
      - backend
    env_file:
      - ./deploy/env/admin.env
    networks:
      - blow

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - frontend
      - admin
      - backend
    command: >-
      /bin/sh -c "\
      if [ ! -f /etc/letsencrypt/live/blow.ru/fullchain.pem ]; then \
        echo 'No TLS certificate found, copying development self-signed bundle.'; \
        mkdir -p /etc/letsencrypt/live/blow.ru; \
        cp /etc/nginx/dev-certs/* /etc/letsencrypt/live/blow.ru/; \
      fi; \
      nginx -g 'daemon off;'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./deploy/nginx/dev-certs:/etc/nginx/dev-certs:ro
      - certbot_challenges:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
      # - uploads_data:/app/uploads:ro 
      - ./blow-be/uploads:/app/uploads:ro 
    networks:
      - blow

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_challenges:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
    networks:
      - blow

volumes:
  mongo_data:
  uploads_data:
  certbot_challenges:
  certbot_certs:

networks:
  blow:
    driver: bridge
