export const ROUTES = {
  HOME: "/",
  OFFER: "/offer",
  ARTICLES: "/articles",
  CONTACTS: "/contacts",
  POLICY: "/privacy",
  RULES: "/rules",
  SEARCH: "/search",
  ACCOUNT: {
    PROFILE: "/account/profile",
    PROFILE_EDIT: "/account/profile/edit",
    GUESTS: "/account/guests",
    DIALOGUES: "/account/dialogues/",
    MAILINGS: "/account/mailings",
    NOTES: "/account/notes",
    SEARCH: "/account/search",
    SERVICES: "/account/services",
    CITY: "/account/city",
  },
  PROFILE: "/profile",
  TEST: "/test",
};
